name: CI

on: [push, pull_request]

jobs:
  vite:
    name: Vite test
    if: always()
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the dependencies
        run: yarn install
      - name: Run the tests
        run: yarn test

  tauri:
    name: Tauri test
    needs: vite
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install the dependencies
        run: yarn install
      - name: Build the application
        run: yarn build
